# SPDX-License-Identifier: GPL-2.0
# LuCI status app for the CR1000A MXL3711 MoCA 2.5 interface.

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI app for MoCA 2.5 (MXL3711) status
LUCI_DEPENDS:=+luci-base
LUCI_PKGARCH:=all

PKG_LICENSE:=GPL-2.0
PKG_MAINTAINER:=Yury Ilyanok <yuryster@gmail.com>

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
